Issue 3 user can view training log
ryan-byrnes/Final-Project pull request #13
Opened 2021-09-17 14:31 UTC by ryan-byrnes

https://user-images.githubusercontent.com/20606439/133800295-09026917-773d-49cd-8419-4709eedf8849.mov

2021-09-17 18:41 UTC, thebearingedge requested changes

2021-09-17 18:41 UTC, thebearingedge commented on client/components/training-session.jsx
> +      });
This doesn't need to be `async/await`.

2021-09-17 18:41 UTC, thebearingedge commented on client/components/training-session.jsx
> +    }
This guard shouldn't be necessary if your initial `trainingSession` is an array. It's safe to call `.map()` on an empty array, it just gives you another empty array.

2021-09-17 18:41 UTC, thebearingedge commented on client/components/training-session.jsx
> +    const sessionDate = date.slice(0, 10);
I don't feel great about this date formatting and slicing thing. Too much hidden intent.

I _think_ you are trying to "floor" the date?

Moment has a way for you to calculate that
https://momentjs.com/docs/#/manipulating/start-of/

And you can then format the string exactly as you want
https://momentjs.com/docs/#/displaying/format/

Using those will help the reader of your code a lot.

2021-09-18 20:29 UTC, ryan-byrnes commented
https://user-images.githubusercontent.com/20606439/133907739-5e25f36c-048e-4a37-9fb7-4469abb860a5.mov

2021-09-18 23:18 UTC, thebearingedge approved these changes

2021-09-19 18:52 UTC, merged